# Nom de l'application
spring.application.name=amazon-prime

# ===== BASE DE DONNEES H2 (developpement) =====
spring.datasource.url=jdbc:h2:mem:streamingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console H2 accessible sur /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== LOGS =====
logging.level.org.springframework.security=INFO
logging.level.com.keyce=DEBUG

# ===== MESSAGES D'ERREUR =====
server.error.include-message=always
spring.main.web-application-type=servlet